// --- Hive generated adapters ---
// These files are generated by hive_generator + build_runner.
// Run: dart run build_runner build --delete-conflicting-outputs
// For now we provide stub adapters so the app compiles without the generator.

import 'package:hive/hive.dart';
import '../models/detection_record.dart';
import '../models/app_settings.dart';

// DetectionRecord adapter stub
class DetectionRecordAdapter extends TypeAdapter<DetectionRecord> {
  @override
  final int typeId = 2;

  @override
  DetectionRecord read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) {
      fields[reader.readByte()] = reader.read();
    }
    return DetectionRecord(
      id: fields[0] as String,
      damageType: fields[1] as DamageType,
      confidence: fields[2] as double,
      latitude: fields[3] as double,
      longitude: fields[4] as double,
      imageUrl: fields[5] as String?,
      detectedAt: fields[6] as DateTime,
      status: fields[7] as DetectionStatus,
      uploaded: fields[8] as bool,
      localImagePath: fields[9] as String?,
      widthMeters: fields[10] as double?,
      depthMeters: fields[11] as double?,
    );
  }

  @override
  void write(BinaryWriter writer, DetectionRecord obj) {
    writer.writeByte(12); // number of fields
    writer.writeByte(0); writer.write(obj.id);
    writer.writeByte(1); writer.write(obj.damageType);
    writer.writeByte(2); writer.write(obj.confidence);
    writer.writeByte(3); writer.write(obj.latitude);
    writer.writeByte(4); writer.write(obj.longitude);
    writer.writeByte(5); writer.write(obj.imageUrl);
    writer.writeByte(6); writer.write(obj.detectedAt);
    writer.writeByte(7); writer.write(obj.status);
    writer.writeByte(8); writer.write(obj.uploaded);
    writer.writeByte(9); writer.write(obj.localImagePath);
    writer.writeByte(10); writer.write(obj.widthMeters);
    writer.writeByte(11); writer.write(obj.depthMeters);
  }
}

// DetectionStatus adapter stub
class DetectionStatusAdapter extends TypeAdapter<DetectionStatus> {
  @override
  final int typeId = 1;

  @override
  DetectionStatus read(BinaryReader reader) {
    return DetectionStatus.values[reader.readByte()];
  }

  @override
  void write(BinaryWriter writer, DetectionStatus obj) {
    writer.writeByte(obj.index);
  }
}

// DamageType adapter stub
class DamageTypeAdapter extends TypeAdapter<DamageType> {
  @override
  final int typeId = 0;

  @override
  DamageType read(BinaryReader reader) {
    return DamageType.values[reader.readByte()];
  }

  @override
  void write(BinaryWriter writer, DamageType obj) {
    writer.writeByte(obj.index);
  }
}

// AppSettings adapter stub
class AppSettingsAdapter extends TypeAdapter<AppSettings> {
  @override
  final int typeId = 3;

  @override
  AppSettings read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) {
      fields[reader.readByte()] = reader.read();
    }
    return AppSettings(
      apiUrl: fields[0] as String? ?? 'http://localhost:8000/api/v1',
      confidenceThreshold: fields[1] as double? ?? 0.65,
      autoUpload: fields[2] as bool? ?? true,
      offlineMode: fields[3] as bool? ?? false,
      mockDetectionMode: fields[4] as bool? ?? false,
      detectionIntervalMs: fields[5] as int? ?? 2000,
      authToken: fields[6] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, AppSettings obj) {
    writer.writeByte(7); // number of fields
    writer.writeByte(0); writer.write(obj.apiUrl);
    writer.writeByte(1); writer.write(obj.confidenceThreshold);
    writer.writeByte(2); writer.write(obj.autoUpload);
    writer.writeByte(3); writer.write(obj.offlineMode);
    writer.writeByte(4); writer.write(obj.mockDetectionMode);
    writer.writeByte(5); writer.write(obj.detectionIntervalMs);
    writer.writeByte(6); writer.write(obj.authToken);
  }
}
